/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonarqube.gradle.test;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Random rand = new Random(); //instance of random class
        int upperbound = 25;
            //generate random values from 0-24
        int int_random = rand.nextInt(upperbound); 
        double double_random=rand.nextDouble();
        float float_random=rand.nextFloat();
    }
}
